server:
  port: 8080

spring:
  application:
    name: orderexecution
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orderexecution
    username: popuser
    password: password
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always