compile:
	dasm *.asm -f3 -v0 -oscreenobjects.bin -lplayfield.lst -splayfield.sym

all:
	dasm *.asm -f3 -v0 -oscreenobjects.bin -lplayfield.lst -splayfield.sym
	stella screenobjects.bin

run:
	stella screenobjects.bin
