compile:
	dasm *.asm -f3 -v0 -ocart.bin -lhorizontalposition.lst -shorizontalposition.sym

all:
	dasm *.asm -f3 -v0 -ocart.bin -lhorizontalposition.lst -shorizontalposition.sym
	stella cart.bin

run:
	stella cart.bin
